export const SUGGESTED_QUERIES = [
  "why is the sky blue",
  "what is a cat",
  "how to build a website",
  "how to sleep while standing",
  "why do birds look at me like that",
  "how to teach physics to a toddler",
  "what happens if I microwave soap",
  "secret ingredient of mayonnaise",
  "how to download more RAM",
  "are whales just big potatoes",
  "history of the unicycle",
  "how to tax-deduct bread crumb collections",
  "why does my plant judge me",
  "is gravity just magnets under the floor",
  "how to explain coffee to a tea leaf",
  "can dogs understand tax laws",
  "why is water wet and is there a dry version",
  "how to win an argument with a microwave",
  "can I use a cabbage as a bicycle helmet",
  "how many teeth does a zipper have",
  "is it safe to high-five a cactus",
  "where do lost socks actually go",
  "why is celery mostly water but crunchy",
  "how to speak fluent hamster",
  "can you train a goldfish to guard a house",
  "how to boil water in a paper cup using solar flares",
  "the ancient mystery of the pencil eraser",
  "what happens if you sneeze on a laptop screen",
  "how to explain modern art to a squirrel",
  "is mayonnaise a valid musical instrument",
  "why does toast always land butter-side down",
  "how to start a business selling cloud shapes",
  "can plants hear me chewing cabbage",
  "history of the third shoe",
  "what is the official currency of dreams",
  "how to paint a blue sky without blue paint",
  "why are onions so emotional",
  "how to make infinite paper airplanes",
  "is my remote control plotting against me",
  "how to build a treehouse for earthworms",
  "can you translate English to Morse code using eyelids",
  "why do cats enjoy sitting inside cardboard squares",
  "how to apologize to a sandwich",
  "what do clouds taste like",
  "is my refrigerator running for president",
  "how to teach a potato to do calculus",
  "why does the moon follow me specifically",
  "can I legally marry a pizza",
  "how to photosynthesis as a human",
  "why do stairs exist if we have legs",
  "is soup just wet salad",
  "how to convince a door it's a window",
  "what is the wifi password for the ocean",
  "can fish get thirsty",
  "how to uninstall gravity",
  "why does my shadow copy everything I do",
  "is there a vitamin for charisma",
  "how to file a complaint against the sun",
  "what language do ants think in",
  "can you overclock a toaster",
  "how to diplomatically break up with a houseplant",
  "why do elevators have trust issues",
  "is the alphabet in alphabetical order on purpose",
  "how to befriend a cloud",
  "what is the square root of a banana",
  "can thoughts get traffic jams",
  "how to outsmart a ceiling fan",
  "why do mirrors show everything backwards except text",
  "is there a support group for people who talk to their cars",
  "how to train my anxiety to be productive",
  "what is the load-bearing capacity of a dream",
  "can I sue my alarm clock for emotional damage",
  "how to explain the internet to a medieval peasant",
  "why do we park in driveways and drive on parkways",
  "is silence just acoustic darkness",
  "how to negotiate with a vending machine",
  "what happens if you water a rock for 100 years",
  "can you grow a money tree from a single penny",
  "how to write a cover letter for a job in another dimension",
  "why do pizzas come in square boxes",
  "is procrastination just time travel for tasks",
  "how to delete someone else's memories",
  "what is the expiration date on a grudge",
  "can furniture have feelings",
  "how to become friends with my future self",
  "why do we say heads up when we should duck",
  "is yawning contagious through text",
  "how to emotionally prepare for a salad",
  "what is the opposite of a spoon",
  "can you tickle yourself if you forget it's coming",
  "how to convince time to slow down on weekends"
];

export const RANDOM_IMAGES = [
  "https://picsum.photos/seed/wrongleimg1/500/400",
  "https://picsum.photos/seed/wrongleimg2/500/400",
  "https://picsum.photos/seed/wrongleimg3/500/400",
  "https://picsum.photos/seed/wrongleimg4/500/400",
  "https://picsum.photos/seed/wrongleimg5/500/400",
  "https://picsum.photos/seed/wrongleimg6/500/400",
  "https://picsum.photos/seed/wrongleimg7/500/400",
  "https://picsum.photos/seed/wrongleimg8/500/400",
  "https://picsum.photos/seed/wrongleimg9/500/400",
  "https://picsum.photos/seed/wrongleimg10/500/400",
  "https://picsum.photos/seed/wrongleimg11/500/400",
  "https://picsum.photos/seed/wrongleimg12/500/400"
];

export const VIDEO_THUMBNAILS = [
  "https://picsum.photos/seed/wronglevid1/350/200",
  "https://picsum.photos/seed/wronglevid2/350/200",
  "https://picsum.photos/seed/wronglevid3/350/200",
  "https://picsum.photos/seed/wronglevid4/350/200",
  "https://picsum.photos/seed/wronglevid5/350/200",
  "https://picsum.photos/seed/wronglevid6/350/200"
];

export const MAP_WIDGET_IMAGES = [
  "https://picsum.photos/seed/wronglemap1/500/300",
  "https://picsum.photos/seed/wronglemap2/500/300",
  "https://picsum.photos/seed/wronglemap3/500/300",
  "https://picsum.photos/seed/wronglemap4/500/300"
];

export const ABSURD_PRODUCTS = [
  { id: 1, title: "Dehydrated Water canister (1 Liter)", price: "$99.99", rating: "4.8", desc: "Just add 1 Liter of fresh water to activate! Guaranteed organic.", imageBg: "bg-blue-100" },
  { id: 2, title: "Pre-cracked Walnuts Monthly Subscription", price: "$49.12 / mo", rating: "1.2", desc: "We mail you walnuts that have already been run over by a tractor. Saves energy.", imageBg: "bg-amber-100" },
  { id: 3, title: "Snail Turtleneck Sweater", price: "$18.50", rating: "4.9", desc: "Keep your garden mollusk warm. 100% synthetic wool, size micro.", imageBg: "bg-purple-100" },
  { id: 4, title: "Portable Black Hole (Gently Used)", price: "$1,450,000", rating: "4.5", desc: "Perfect for cleaning closets. Minor gravity spikes expected. Non-returnable.", imageBg: "bg-slate-900" },
  { id: 5, title: "Inflatable Accordion Simulator (Silent)", price: "$34.99", rating: "3.1", desc: "For public transit musicians who value silence. Heavy vinyl build.", imageBg: "bg-green-100" },
  { id: 6, title: "Inverted Umbrella (For collecting rain)", price: "$29.00", rating: "4.0", desc: "Holds up to 2 gallons. Funnels everything directly down your sleeve.", imageBg: "bg-amber-100" }
];

export const ABSURD_VIDEOS = [
  { id: 1, title: "DIY: Paving your driveway with wet sourdough starter", creator: "Grandmaster Barnaby", views: "14B views", duration: "1:44:02", category: "Baking" },
  { id: 2, title: "How I escaped a giant squid using custom-built toaster engines", creator: "Submarine Steve", views: "203 views", duration: "45:12", category: "Adventure" },
  { id: 3, title: "10 Hours of relaxing lawnmower sounds (played backwards on flute)", creator: "The Flute Wizard", views: "8.9M views", duration: "10:00:00", category: "Music" },
  { id: 4, title: "Calibrating your cat's olive oil level - Professional Tutorial", creator: "Ancient Egyptian Tech Support", views: "4.2K views", duration: "12:15", category: "Felines" },
  { id: 5, title: "The secret banking cartel made entirely of Swiss cheese", creator: "Luminous Truth", views: "900M views", duration: "2:10:05", category: "Finance" }
];

export const HUMOROUS_FEEDBACK_REPLIES = [
  "We have registered your request. An imaginary representational clerk has been assigned to stand in a corner and contemplate your review for 45 minutes.",
  "Thank you for your feedback. Our automated filters have detected high volumes of common sense in your message. It was swiftly redirected to the compost bin.",
  "Submission logged! We have dispatched a carrier pigeon with a microfiche copy of your review directly to the central archives at the Mariana Trench.",
  "Review filed. To show our gratitude, we have increased your pet snail's imaginary wool production allowance by +14% for this fiscal quarter."
];
